'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Films', [
        {
            title: "3 Godfathers",
            production_co: "MGM Pictures",
            release: "1948-12-01",
            last_viewed: "2016-12-24",
            my_rating: "9",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BNjNmMzE5MzEtZmM3YS00ODljLWI1YTEtMWU1MmMyZGNiODg1XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_SX300.jpg",
            set: "Greatest Classic Films Collection: John Ford Westerns DVD",
            poster: "TRUE",
            night_at_the_movies: "TRUE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "Western",
            storyline: "Three outlaws on the run discover a dying woman and her baby. They swear to bring the infant to safety across the desert, even at the risk of their own lives.",
            comments: "Seems a little cornier than I remembered it.  Ford's picture painting as good as ever.  Including great Arizona scenery.  Ford's movies always have the best-looking horses.  Every shot is wonderfully arranged, and is a painted picture.  Perfectly framed.  Attention is even paid to the tracks, so that they an artistic pattern within the picture.  This story is a touch choppy.  Partly the story, partly Ford's picture-tableaus.  Ford used is usual screenwriters, so I'm sure the screenplay was influenced by him as well.  The theme is pure American fable of course; even criminals have heart.",
            city: "Welcome-fictional",
            state: "AZ",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()

        },
        {
            title: "High Noon",
            production_co: "Stanley Kramer Productions",
            release: "1952-07-30",
            my_rating: "10",
            afi_top_100: "27",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BOWIzZGUxZmItOThkMS00Y2QxLTg0MTYtMDdhMjRlNTNlYTI3L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "TRUE",
            nbr_of_discs: "1",
            genre: "Western",
            storyline: "On the day he gets married and hangs up his badge, lawman Will Kane is told that a man he sent to prison years before, Frank Miller, is returning on the noon train to exact his revenge. Having initially decided to leave with his new spouse, Will decides he must go back and face Miller. However, when he seeks the help of the townspeople he has protected for so long, they turn their backs on him. It seems Kane may have to face Miller alone, as well as the rest of Miller's gang, who are waiting for him at the station... ",
            city: "Hadleyville-fictional",
            state: "NM",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "High Sierra",
            production_co: "Warner Bros Pictures",
            release: "1941-01-25",
            last_viewed: "2013-07-11",
            my_rating: "10",
            my_top_ten: "9",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BYzg2MzBjNWUtMDgyZS00ZWFmLTljMDEtZmUxMTEwNGM4M2RlXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg",
            set: "Humphrey Bogart: Signature Collection - Volume 1 DVD",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "Film Noir",
            storyline: "Roy 'Mad Dog' Earle is broken out of prison by an old associate who wants him to help with an upcoming robbery. When the robbery goes wrong and a man is shot and killed Earle is forced to go on the run, and with the police and an angry press hot on his tail he eventually takes refuge among the peaks of the Sierra Nevadas, where a tense siege ensues. But will the Police make him regret the attachments he formed with two women during the brief planning of the robbery.og' Earle is broken out of prison by an old associate who wants him to help with an upcoming robbery. When the robbery goes wrong and a man is shot and killed Earle is forced to go on the run, and with the police and an angry press hot on his tail he eventually takes refuge among the peaks of the Sierra Nevadas, where a tense siege ensues. But will the Police make him regret the attachments he formed with two women during the brief planning of the robbery.",
            comments: "Awesome performance by both Ida Lupino and Humphrey Bogart.  Raoul Walsh's style is straightforward, but the story and the acting completely overcome that.  Still, Walsh made strong use of low-key lighting to heighten overall suspense.  Walsh insisted on shooting the mountain scenes on location, a divergence from his normal style in some ways, allowing him to take angle-shots which added greatly to the drama and suspense.  Roy Earle's character is drawn from John Dillinger.  The visual similarity is immediately noticeable.  If that's not enough, Huston pounds it home with Roy's trip to his rural home in Indiana.  Velma is the symbol of \"good\", which Roy has not known, presumably by the choices that he has made.  Her rejection of him is a metaphor, a sign that he can no longer turn back, he is \"bad\", and that is now his fate.  Marie is like Roy, and is also unable to stop the coming events.  Marie in a way also represents \"good\", but Roy will not be able enjoy any happines with her.  Again, fate will not permit it.  Pard - the dog - is ugly, cute, eerie and comical.  Pard represents fate - forever chasing Roy, without fail bringing Roy's fate and laying it at his feet.",
            city: "Los Angeles",
            state: "CA",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "3:10 to Yuma",
            production_co: "LionsGate",
            release: "2007-09-07",
            last_viewed: "2017-05-07",
            my_rating: "9",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BODE0NTcxNTQzNF5BMl5BanBnXkFtZTcwMzczOTIzMw@@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "TRUE",
            nbr_of_discs: "1",
            genre: "Western",
            storyline: "Rancher Dan Evans heads into Bisbee to clear up issues concerning the sale of his land when he witnesses the closing events of a stagecoach robbery led by famed outlaw Ben Wade. Shortly thereafter, Wade is captured by the law in Bisbee and Evans finds himself one of the escorts who will take Wade to the 3:10 to Yuma train in Contention for the reward of $200. Evans's effort to take Wade to the station is in part an effort to save his land but also part of an inner battle to determine whether he can be more than just a naive rancher in the eyes of his impetuous and gunslinging son William Evans. The transport to Contention is hazardous and filled with ambushes by Indians, pursuits by Wade's vengeful gang and Wade's own conniving and surreptitious demeanor that makes the ride all the more intense.",
            city: "Contention City-fictional",
            state: "AZ",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "After The Thin Man",
            production_co: "MGM Pictures",
            release: "1936-12-25",
            last_viewed: "2014-03-14",
            my_rating: "7",
            format: "https://m.media-amazon.com/images/M/MV5BYWNjMTRkOGMtOGMyZS00NTNlLTg5ZTctYTEzMWM1ZDExZjgzXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "TRUE",
            genre: "Comedy-Crime-Mystery",
            storyline: "Now back in San Francisco after their holiday in New York, Nick and Nora find themselves trying to solve another mystery. It's New Year's Eve and they are summoned to dinner at Nora's elderly, and very aristocratic, family. There they find that cousin Selma's husband Robert has been missing for three days. Nick reluctantly agrees to look for him but the case takes a twist when Robert is shot and Selma is accused of murder. Several other murders occur but eventually Nick gathers everyone into the same room to reveal the identity of the killer.",
            comments: "More of the same.  Mostly William Powell and  Myrna Loy being funny and charming.  They did have excellent chemistry.",
            city: "San Francisco",
            state: "CA",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "300",
            production_co: "Warner Bros Pictures",
            release: "2007-03-09",
            last_viewed: "2013-03-19",
            my_rating: "9",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BNWMxYTZlOTUtZDExMi00YzZmLTkwYTMtZmM2MmRjZmQ3OGY4XkEyXkFqcGdeQXVyMTAwMzUyMzUy._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "War",
            storyline: "In the Battle of Thermopylae of 480 BC an alliance of Greek city-states fought the invading Persian army in the mountain pass of Thermopylae. Vastly outnumbered, the Greeks held back the enemy in one of the most famous last stands of history. Persian King Xerxes lead a Army of well over 100,000 (Persian king Xerxes before war has about 170,000 army) men to Greece and was confronted by 300 Spartans, 700 Thespians and other Slave soldiers. Xerxes waited for 10 days for King Leonidas to surrender or withdraw left with no options he moved. The battle lasted for about 3 days and after which all 300 Spartans were killed. The Spartan defeat was not the one expected, as a local shepherd, named Ephialtes, defected to the Persians and informed Xerxes of a separate path through Thermopylae, which the Persians could use to outflank the Greeks.",
            comments: "CGI enhanced based on Frank Miller's Graphic Novel of the same title.  Outstanding effects and outstanding visual artistry and composition.  Techniques employed in graphic novels are utilized and enhanced with captivating results.",
            city: "Thermopalae",
            country: "Greece",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Anatomy of a Murder",
            production_co: "Carlyle Productions",
            release: "1959-07-01",
            last_viewed: "2006-10-30",
            my_rating: "10",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BMzM0MzE2ZTAtZTBjZS00MTk5LTg5OTEtNjNmYmQ5NzU2OTUyXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg",
            set: "Anatomy of a Murder: The Criterion Collection DVD",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "2",
            genre: "Film Noir",
            storyline: "Frederick Manion (Ben Gazzara), a lieutenant in the army, is arrested for the murder of a bartender, Barney Quill. He claims, in his defense, that the victim had raped and beaten up his wife Laura (Lee Remick). Although Laura supports her husband's story, the police surgeon can find no evidence that she has been raped. Manion is defended by Paul Biegler (James Stewart), a rather humble small-town lawyer. During the course of interviews, Biegler discovers that Manion is violently possessive and jealous, and also that his wife has a reputation for giving her favors to other men. Biegler realizes that the prosecution will try to make the court believe that Laura was the lover of the bartender and than Manion killed him and beat her up when he discovered them together. Manion pleads \"not guilty\" and Biegler, who knows that his case is weak, sets his assistants to try to find a witness who will save Manion.",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Hong Kong Confidential",
            production_co: "Robert E. Kent Productions",
            release: "1958-10-15",
            last_viewed: "2015-07-31",
            my_rating: "3",
            format: "https://m.media-amazon.com/images/M/MV5BZThjMjdiY2MtYzVlMS00NzY2LTlhMGYtMmJmNTYwZWQyZmMxXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Drama-Thriller",
            storyline: "Secret agent Casey Reed is assigned to locate a missing Arab prince kidnapped by Communists who hope to force the prince's father, king of the small Arab nation of Thamen, to cancel the signing of an agreement allowing a US missile base in his country. Reed, fronting as a nightclub singer with his unsuspecting girlfriend Fay, gets a lead which ultimately leads to his capture by the Communists. He learns that he and the Arab prince are both to be killed in order to blame the kidnapping on the US.",
            comments: "I skipped through this one.  Didn't watch it through.  Corny.  Bad story, bad acting, bad composition, bad musical score, bad directing.  Elements of 007 movies that were to soon follow.  But, hard to see it, since it was so bad.",
            city: "Hong Kong",
            state: "Hong Kong",
            country: "China",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Blade Runner",
            production_co: "Ladd Company",
            release: "1982-06-25",
            last_viewed: "2014-07-15",
            my_rating: "8",
            format: "https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "SciFi-Thriller",
            storyline: "In a cyberpunk vision of the future, man has developed the technology to create replicants, human clones used to serve in the colonies outside Earth but with fixed lifespans. In Los Angeles, 2019, Deckard is a Blade Runner, a cop who specializes in terminating replicants. Originally in retirement, he is forced to re-enter the force when four replicants escape from an off-world colony to Earth",
            city: "Los Angeles",
            state: "CA",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Blade Runner 2049",
            production_co: "Warner Bros Pictures",
            release: "2017-10-06",
            last_viewed: "2019-01-26",
            my_rating: "9",
            format: "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "SciFi-Thriller",
            storyline: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K (Ryan Gosling), unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard (Harrison Ford), a former LAPD blade runner who has been missing for 30 years.",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Mulholland Falls",
            production_co: "MGM Pictures",
            release: "1996-04-26",
            last_viewed: "2013-07-07",
            my_rating: "6",
            format: "https://m.media-amazon.com/images/M/MV5BOTcwMDE3MTQ5OV5BMl5BanBnXkFtZTcwMzA0MDQ1NA@@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Drama-Crime",
            storyline: "This film is about the adventures of a 1940's special anti-gangster police squad in Los Angeles, the infamous 'Hat Squad.' The four members of this squad are big, tough, no-nonsense cops who don't hesitate to break the law, if it suits their purposes. When a local woman is murdered, their investigation turns up the fact that she had been romantically linked to several prominent men and had secret films taken of her liaisons. Since one of those men is the powerful U.S. Army General at the head of the then-new Atomic Energy Commission and another is the (married) leader of the Hat Squad, complications ensue. The FBI even gets involved in an attempted cover-up.",
            comments: "Excellent late 1940s sets, cars, costumes.  Interesting story and drama.  But, did not have any key-lighting.  Straight, hard story and story-telling.",
            city: "Los Angeles",
            state: "CA",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "It Happened on Fifth Avenue",
            production_co: "Roy Del Ruth Productions",
            release: "1947-04-19",
            last_viewed: "2014-12-25",
            my_rating: "8",
            format: "https://m.media-amazon.com/images/M/MV5BYjA5ZGUxZWEtYTYyYS00YTZiLWJiODktY2NiYzBlZGE5ZGY0XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Comedy-Romance",
            storyline: "A homeless New Yorker moves into a mansion and along the way he gathers friends to live in the house with him. Before he knows it, he is living with the actual home owners.",
            comments: "Funny.  Charming.  Light-hearted and well-performed.  Excellent chemistry between the characters/performers who all let their personality and kindness show through.",
            city: "New York",
            state: "NY",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "It Happened One Night",
            production_co: "Columbia Pictures",
            release: "1934-02-23",
            last_viewed: "2017-05-02",
            my_rating: "7",
            afi_top_100: "46",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BYzJmMWE5NjAtNWMyZS00NmFiLWIwMDgtZDE2NzczYWFhNzIzXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "TRUE",
            nbr_of_discs: "1",
            genre: "Comedy-Romance",
            storyline: "Ellie Andrews has just tied the knot with society aviator King Westley when she is whisked away to her father's yacht and out of King's clutches. Ellie jumps ship and eventually winds up on a bus headed back to her husband. Reluctantly she must accept the help of out-of- work reporter Peter Warne. Actually, Warne doesn't give her any choice: either she sticks with him until he gets her back to her husband, or he'll blow the whistle on Ellie to her father. Either way, Peter gets what (he thinks!) he wants .... a really juicy newspaper story.",
            comments: "Fun.  Capra-esque of course.  Witty dialogue.  Of course, the beginning of the genre.  The key for these movies is that the couple have chemistry.  And, Clark Gable and Claudette Colbert do have chemistry.  For an excellent example of this genre, with multiple parallels - watch \"Leap Year\".  While this movie shows the scene of leaving the jerk at the altar, \"Leap Year\" shows the \"reunion\", which improves the exclaimation point at the end.",
            city: "New York",
            state: "NY",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "It's a Wonderful Life",
            production_co: "Liberty Films",
            release: "1947-01-07",
            last_viewed: "2014-12-06",
            my_rating: "7",
            afi_top_100: "20",
            format: "https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Drama-Fantasy",
            storyline: "George Bailey has spent his entire life giving of himself to the people of Bedford Falls. He has always longed to travel but never had the opportunity in order to prevent rich skinflint Mr. Potter from taking over the entire town. All that prevents him from doing so is George's modest building and loan company, which was founded by his generous father. But on Christmas Eve, George's Uncle Billy loses the business's $8,000 while intending to deposit it in the bank. Potter finds the misplaced money and hides it from Billy. When the bank examiner discovers the shortage later that night, George realizes that he will be held responsible and sent to jail and the company will collapse, finally allowing Potter to take over the town. Thinking of his wife, their young children, and others he loves will be better off with him dead, he contemplates suicide. But the prayers of his loved ones result in a gentle angel named Clarence coming to earth to help George...",
            comments: "Very good christmas holiday story. Norman Rockwell Americana themes abound - making this film a classic based partly on it's cliches.  The lines are corny at times of course.  But the performances are excellent given the circumstances.  Donna Reed brings chemistry with James Stewart to the film.  Wonderful American Hollywood ending.  This is a good movie.",
            city: "Bedford Falls",
            state: "NY",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Jeremiah Johnson",
            production_co: "Warner Bros Pictures",
            release: "1972-09-10",
            last_viewed: "2014-04-13",
            my_rating: "8",
            format: "https://m.media-amazon.com/images/M/MV5BYzE0NWI0ZDctYjkwNi00YTM3LWI4MjYtZGRlN2JiMjZmYzY3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Western",
            storyline: "A mountain man who wishes to live the life of a hermit becomes the unwilling object of a long vendetta by Indians when he proves to be the match of their warriors in one-to-one combat on the early frontier. ",
            comments: "No  foreshadowings, no metaphors, no visual tapestry.  Excellently filmed to be sure.  But basically, a good basic and engaging story.  Good action.  Well-acted.  Particularly Ally Ann McLerie as a crazy woman.  Excellent western wilderness location scenery.  And yes, tragic, with the advantage of many Westerns, the hero at least gets revenge.",
            city: "Western US",
            state: "Western US",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Johnny Mnemonic",
            production_co: "TriStar Pictures",
            release: "1995-05-26",
            last_viewed: "2015-06-20",
            my_rating: "5",
            format: "https://m.media-amazon.com/images/M/MV5BNTdhYjEzYTEtYTkwZC00NzgxLWI0ZWEtYmEyMGZhOWYwMjE2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "SciFi",
            storyline: "In 2021, the whole world is connected by the gigantic Internet, and almost a half of the population is suffering from the Nerve Attenuation Syndrome (NAS).Johnny with an inplanted memory chip in his brain was ordered to transport the over loaded information from Beijing to Newark. While Pharmakom Industries supported by yakuza tries to capture him to get the informaiton back, the Low-tech group led by J-Bone tries to break the missing code to download the cure of NAS which Johnny carries.",
            comments: "Part \"Blade Runner\", part \"Escape from New York\", part \"The Matrix\".  There's some use of symbolism, a complex plot, a dark surreal world.  The dialogue is cheesy - making the acting cheesy.  The special effects were excellent for the time.",
            city: "Newark",
            state: "NJ",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Jumper",
            release: "2008-02-14",
            last_viewed: "2012-07-16",
            my_rating: "7",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BMjEwOTkyOTI3M15BMl5BanBnXkFtZTcwNTQxMjU1MQ@@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "SciFi",
            storyline: "David Rice is a high school student in Ann Arbor, abandoned by his mother at five, enamored with Millie, a fellow student, and picked on by at least one classmate. On a winter's day, while about to drown, he discovers he can transport himself instantaneously to anyplace on earth. He leaves town, goes to New York City, robs a bank vault, and comes to the attention of a shadowy group of government hunters. Eight years later, the hunters, led by the murderous Roland, get a fix on David. He heads home, searches out Millie, invites her to travel with him, and only later realizes that Roland and his crew are seriously deadly. Is everyone close to David in danger? ",
            comments: "Suspenseful.  Special effects are excellent and enhance the suspense, as well as providing great action.  Some clue shots.",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Tron",
            production_co: "Walt Disney Pictures",
            release: "1982-07-09",
            last_viewed: "2013-08-12",
            my_rating: "7",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BMzZhNjYyZDYtZmE4MC00M2RlLTlhOGItZDVkYTVlZTYxOWZlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "SciFi",
            storyline: "Hacker/arcade owner Kevin Flynn is digitally broken down into a data stream by a villainous software pirate known as the Master Control and reconstituted into the internal, 3-D graphical world of computers. It is there, in the ultimate blazingly colorful, geometrically intense landscapes of cyberspace, that Flynn joins forces with Tron to outmaneuver the Master Control program that holds them captive in the equivalent of a gigantic, infinitely challenging computer game.",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Tron: Legacy",
            production_co: "Walt Disney Pictures",
            release: "2010-12-17",
            last_viewed: "2013-02-08",
            my_rating: "7",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BMTk4NTk4MTk1OF5BMl5BanBnXkFtZTcwNTE2MDIwNA@@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "SciFi",
            storyline: "Sam Flynn, the tech-savvy 27-year-old son of Kevin Flynn, looks into his father's disappearance and finds himself pulled into the same world of fierce programs and gladiatorial games where his father has been living for 20 years. Along with Kevin's loyal confidant, father and son embark on a life-and-death journey across a visually-stunning cyber universe that has become far more advanced and exceedingly dangerous.",
            comments: "Excellent sequel to \"Tron\".  Numerous references to the original story in the plot.  The visual CGI artistry is both an homage to the original, completely true to its spirit and theme, and an outstanding update with brighter colors, and greater detail of the clothing and \"the grid\" computer environment.  The motorcycles are realistic updates of the originals from Tron.  They look like you could get on and ride them.  All the old games and toys are there as well (except the M-tanks).  Love the Ducati in the real world.  Also, the architecture is noticeable throughout; and I particularly like the Flynn home with its simple shed architecture style with vaulted ceiling and clean white interior, large windows and LOTs of bookshelves, and Sam Flynn's container stack home with (again) large windows, garage doors right to the open, austere living room, that includes space for his motorcycle and workshop.",
            country: "Computer",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Trouble with the Curve",
            production_co: "Warner Bros Pictures",
            release: "2012-09-21",
            last_viewed: "2013-06-01",
            my_rating: "8",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BMTUwNjMyMzQ3M15BMl5BanBnXkFtZTcwMjcwNDMyOA@@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "Drama",
            storyline: "Gus is a baseball scout. The team he works for thinks he should retire. He asks them to let him do one more scouting job to prove himself. His friend, Pete, asks Gus's estranged daughter, Mickey, if she could go with him to make sure he's OK as his eyes are failing. The doctor tells Gus he should get his eyes treated but he insists on doing his scouting assignment, which takes him to North Carolina. Mickey decides to put her work on hold to go with him and she wants him to explain why he pushed her away. Whilst there he runs into Johnny, a scout from another team who was a promising player Gus once scouted. Johnny and Mickey take an interest in each other.",
            city: "Atlanta",
            state: "GA",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "True Detective - Season 1",
            production_co: "HBO",
            release: "2014-03-09",
            last_viewed: "2014-03-09",
            my_rating: "10",
            format: "https://m.media-amazon.com/images/I/51Py3cxpf5L.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Drama-Crime",
            storyline: "The lives of two detectives, Rust Cohle and Martin Hart, become entangled during a 17-year hunt for a serial killer in Louisiana.",
            comments: "Dark, twisted, cerebral, taut, gritty, complex crime drama.  Compelling - even additive.  Outstanding acting performances by Matthew Maconahay and Woody Harrelson.  The entire cast gave outstanding performances.",
            city: "Various",
            state: "LA",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "True Detective - Season 2",
            production_co: "HBO",
            release: "2015-06-21",
            last_viewed: "2015-06-21",
            my_rating: "9",
            format: "https://m.media-amazon.com/images/I/5172ZYFwMrL.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Drama-Crime",
            storyline: "The disappearance of a city manager disrupts a lucrative land scheme and ignites an investigation involving three police officers and a career criminal who is moving into legitimate business.",
            comments: "Dark, twisted, cerebral, taut, gritty, complex crime drama.  Compelling - even additive.  Awesome visuals, awesome soundtracks.  Some style differences from season one.  This is not a re-done version of the first season.  Can't wait for season 3.",
            city: "Various",
            state: "LA",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "13 Rue Madeleine",
            production_co: "20th Century Fox",
            release: "1947-03-03",
            last_viewed: "2014-01-11",
            my_rating: "5",
            format: "https://m.media-amazon.com/images/M/MV5BZjE4ZDMxNzctMTljMy00NGE4LTljNGMtN2RmZmMyYTU1ZWJhXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Action-Adventure",
            storyline: "Documentary-style prologue follows training of O.S.S. agents for WWII work behind enemy lines. One of the group is a German \"mole;\" leaders Gibson and Sharkey are aware of this and scheme to feed him false info about the invasion of Europe, while the real agents go to France to find a secret V-2 rocket depot. But the German spy outsmarts them and rejoins his people knowing too much; Bob Sharkey takes the risk of going in after him. ",
            comments: "Yep.  Documentary style.  Tedious. Staged scenes. Descent cinematography.  How do you make a spy movie boring?",
            city: "Paris",
            state: "Île-de-France",
            country: "France",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Dead Reckoning",
            production_co: "Columbia Pictures",
            release: "1947-01-16",
            last_viewed: "2015-02-04",
            my_rating: "10",
            my_top_ten: "10",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BOTY0NDcyZGYtZTFhMS00YTA0LThlMzQtODQ4NTlhNzhkZmE2XkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "TRUE",
            nbr_of_discs: "1",
            genre: "Film Noir",
            storyline: "Rip Murdock and Johnny Darke are en route to Washington when Johnny disappears and then turns up dead. Rip learns that Johnny had been accused of murder and sets out to find out what he can. He falls in love with Coral whose husband Johnny is supposed to have killed. ",
            comments: "I just like the story and the pace.  There is mystery that Murdoch unravels through brains and some hard work.  There are plot twists and red herrings.  Excellent gritty stacatto dialogue delivered very well by Bogart and Scott.  Excellent key-lighting.  At certain key points, Bogart is actually completely in silhouette.  Nice legs, husky voice.  The only \"metaphor\" that I caught was when Murdoch is in love with Coral he calls her by the pet name that he gaver her - \"Mike\".  When he's mad at her or distrusts her, he calls her by the pet name that Johnny gave her - \"Dusty\".",
            city: "Gulf City",
            state: "FL",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "A Fistful of Dollars",
            production_co: "Constantin Film Produktion",
            release: "1964-10-16",
            last_viewed: "2011-12-29",
            my_rating: "8",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BYjA1MGVlMGItNzgxMC00OWY4LWI4YjEtNTNmYWIzMGUxOGQzXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UY1200_CR97,0,630,1200_AL_.jpg",
            set: "The Man with No Name Trilogy",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "Western",
            storyline: "An anonymous, but deadly man rides into a town torn by war between two factions, the Baxters and the Rojo's. Instead of fleeing or dying, as most other would do, the man schemes to play the two sides off each other, getting rich in the bargain.",
            comments: "Suspense generated by the anonymity of the protaganist.  His goals and motives are unknown.  Drawn out scenes of sweaty tension.  Everyone moves slowly to conserve energy.  But, this also portrays caution from constant danger.  This story/film is more straightforward than the others in the trilogy.  It's basic good triumphs over evil, with the twist of the \"good\" being tougher, and on the outside, as heartless as the bad.  Thus, becoming the building block for the following movies of the trilogy.",
            city: "Western US",
            state: "Western US",
            country: "united States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "In Time",
            production_co: "20th Century Fox",
            release: "2011-10-28",
            last_viewed: "2014-02-09",
            my_rating: "9",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BMjA3NzI1ODc1MV5BMl5BanBnXkFtZTcwMzI5NjQwNg@@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "SciFi-Thriller",
            storyline: "Welcome to a world where time has become the ultimate currency. You stop aging at 25, but there's a catch: you're genetically-engineered to live only one more year, unless you can buy your way out of it. The rich \"earn\" decades at a time (remaining at age 25), becoming essentially immortal, while the rest beg, borrow or steal enough hours to make it through the day. When a man from the wrong side of the tracks is falsely accused of murder, he is forced to go on the run with a beautiful hostage. Living minute to minute, the duo's love becomes a powerful tool in their war against the system. ",
            comments: "Suspenseful.  The premise of the plot itself means that the \"clock\" keeps getting to start over again, restarting the suspense.  Well-acted by Justin and Amanda.  There's action too.  Some use of symbolism, even more use of double-entendre of time-related phrases.  There are multiple mirror scenes, including Justin and his Mom racing toward each other to save her life/Justin and Amanda racing toward each other to save her life.",
            city: "Dayton",
            state: "OH",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Inception",
            production_co: "Warner Bros Pictures",
            release: "2010-07-16",
            last_viewed: "2012-04-11",
            my_rating: "8",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "SciFi",
            storyline: "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible-inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.",
            comments: "Suspenseful, accentuated with a plot built on multiple levels.  Outstanding special-effects that build the story, not just portray it.  Well-acted.  Elements of darkness (visual and musical) included both add to the suspense and drama, as well as create the sense of being in the dark recesses of the mind.  Outstanding story. (Ariadne, daughter of Cretan king Minos, helped Theseus escape from the Cretan labyrinth.)",
            country: "Dreamland",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "47 Ronin",
            production_co: "H2F Entertainment",
            release: "2013-12-25",
            last_viewed: "2013-12-28",
            my_rating: "5",
            format: "https://m.media-amazon.com/images/M/MV5BMTc0MjE2NzE0OV5BMl5BanBnXkFtZTgwNTU5MjE1MDE@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Drama-Action",
            storyline: "An 18th century set story centered on a band of samurai who set out to avenge the death of their master. ",
            comments: "I saw this at the theater in 3D.  A mix of CGI enhanced depiction of Japanese magical legend, and seemingly realistic feudal Japanese settings and landscapes. Excellent incorporation, enhancement and use of color.  I'm not versed on the original 47 Ronin story/legend.  But it seemed that liberties were taken with these stories for the sake of the commercial and/or magical components of this film.  The realistic and the magical seemed at odds with each other in the film.  The realistic elements seemed to be capable of standing on their own as a captivating story.  Also, not sure about the inclusion of the \"halfbreed\" in the storyline.  I suspect that was a way to get Keannu into the story.  The fighting sequences were enhanced, and so did not carry the gritiness of a genuine hand-to-hand martial arts combat.",
            city: "Tokyo",
            state: "Kanto",
            country: "Japan",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "The Godfather",
            production_co: "Paramount Pictures",
            release: "1972-03-24",
            last_viewed: "2014-01-25",
            my_rating: "10",
            afi_top_100: "2",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "Drama-Crime",
            storyline: "The story begins as \"Don\" Vito Corleone, the head of a New York Mafia \"family\", oversees his daughter's wedding. His beloved son Michael has just come home from the war, but does not intend to become part of his father's business. Through Michael's life the nature of the family business becomes clear. The business of the family is just like the head of the family, kind and benevolent to those who give respect, but given to ruthless violence whenever anything stands against the good of the family. Don Vito lives his life in the way of the old country, but times are changing and some don't want to follow the old ways and look out for community and \"family\". An up and coming rival of the Corleone family wants to start selling drugs in New York, and needs the Don's influence to further his plan. The clash of the Don's fading old world values and the new ways will demand a terrible price, especially from Michael, all for the sake of the family.",
            comments: "Straight drama.  Powerful drama, with novelty of italian crime family culture, customs and power struggles.  Story of Michael Corleone's descent/ascension to the Don(Godfather) of the Corleone mafia family.  Michael's loss of himself, and ascension to Godfather are portrayed as inevitable, and each step in the march is portrayed one by one.",
            city: "New York",
            state: "NY",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "The Godfather Part III",
            production_co: "Paramount Pictures",
            release: "1990-12-25",
            last_viewed: "2014-01-26",
            my_rating: "9",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BNWFlYWY2YjYtNjdhNi00MzVlLTg2MTMtMWExNzg4NmM5NmEzXkEyXkFqcGdeQXVyMDk5Mzc5MQ@@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "Drama-Crime",
            storyline: "In the final instalment of the Godfather Trilogy, an aging Don Michael Corleone seeks to legitimize his crime family's interests and remove himself from the violent underworld but is kept back by the ambitions of the young. While he attempts to link the Corleone's finances with the Vatican, Michael must deal with the machinations of a hungrier gangster seeking to upset the existing Mafioso order and a young protoge's love affair with his daughter. ",
            comments: "Straight drama.  Initially, seemingly less power and drama of the previous installments.  But the story picks up as Michael Corleone begins to pursue control of a major international company through political maneuvering with the vatican.  He seems to have finally pulled himself and his family out of organized crime.  And he even fights to take a path to legitimacy.  But events, his own family, and his ambitious move to control an International conglomerate corporation all work against him.  The ultimate tragedy seems inevitable.  There are numerous repeated phrases and symbolic parallel scenes, emphasizing the inevitibility of the current events. His greatest treasure - his beautiful daughter who loves him apparently in spite of his known past, is killed by a failed assasination attempt on Michael Corleone just as he is on the verge of the triumph of becoming legitimate, and reconciling with his ex-wife, son, and daughter, and exiting organized crime. Outstanding acting performances.  Some use of visual imagery.  Well done screenplay.",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "The Godfather: Part II",
            production_co: "Paramount Pictures",
            release: "1974-12-20",
            last_viewed: "2014-01-26",
            my_rating: "10",
            afi_top_100: "32",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "TRUE",
            nbr_of_discs: "1",
            genre: "Drama-Crime",
            storyline: "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba. ",
            comments: "Straight drama.  Powerful drama, with novelty of italian crime family culture, customs and power struggles.  Continued conflict of Michael Corleone with himself, sacrificing his humanity and compassion for the sake his family and legacy.  Complex plot.  The parallel story-telling of Vito's ascension to power and Michael's \"descent\" into the next level hell give great depth to the story and help to emphasize how \"history\" of Sicily and of the family impacted Michael's and everyone's behavior and decisions. Outstanding acting performances.  Amazing realistic sets of Italy, New York, NY, Las Vegas, NV, Miami, FL, Havana, Cuba in various periods.",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "300",
            production_co: "Warner Bros Pictures",
            release: "2007-03-09",
            last_viewed: "2013-03-19",
            my_rating: "9",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BNWMxYTZlOTUtZDExMi00YzZmLTkwYTMtZmM2MmRjZmQ3OGY4XkEyXkFqcGdeQXVyMTAwMzUyMzUy._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "War",
            storyline: "In the Battle of Thermopylae of 480 BC an alliance of Greek city-states fought the invading Persian army in the mountain pass of Thermopylae. Vastly outnumbered, the Greeks held back the enemy in one of the most famous last stands of history. Persian King Xerxes lead a Army of well over 100,000 (Persian king Xerxes before war has about 170,000 army) men to Greece and was confronted by 300 Spartans, 700 Thespians and other Slave soldiers. Xerxes waited for 10 days for King Leonidas to surrender or withdraw left with no options he moved. The battle lasted for about 3 days and after which all 300 Spartans were killed. The Spartan defeat was not the one expected, as a local shepherd, named Ephialtes, defected to the Persians and informed Xerxes of a separate path through Thermopylae, which the Persians could use to outflank the Greeks.",
            comments: "CGI enhanced based on Frank Miller's Graphic Novel of the same title.  Outstanding effects and outstanding visual artistry and composition.  Techniques employed in graphic novels are utilized and enhanced with captivating results.",
            city: "Thermopalae",
            country: "Greece",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "300: Rise of an Empire",
            production_co: "Warner Bros Pictures",
            release: "2014-03-07",
            last_viewed: "2014-03-13",
            my_rating: "7",
            format: "https://m.media-amazon.com/images/M/MV5BMTEwNTU2MjAwMDdeQTJeQWpwZ15BbWU3MDk2Njc2Njk@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Drama-Action",
            storyline: "After its victory over Leonidas' 300, the Persian Army under the command of Xerxes marches south towards the major Greek city-states. The Democratic city of Athens, first on the path of Xerxes' army, bases its strength on its fleet, led by admiral Themistocles. Themistocles is forced to an unwilling alliance with the traditional rival of Athens, oligarchic Sparta whose might lies with its superior infantry troops. But Xerxes still reigns supreme in numbers over sea and land.",
            comments: "This film followed the formula of the first movie.  But the dramatic results weren't the same.  Partly because the dramatic elements of the historical event did not have the same punch as the original.  Entertaining.  Excellent CGI and interweaving of myth, legend and historical events.  I guess I still hoped for/expected more.",
            country: "Agean Sea",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Winchester '73",
            production_co: "Universal Pictures",
            release: "1950-07-12",
            last_viewed: "2012-03-20",
            my_rating: "10",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BZmI1ZmJkMzgtODE1My00OTMxLTkwYjktOWYwMWQ1ZDgzNDk2XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_SX300.jpg",
            set: "The James Stewart Hollywood Legend Collection DVD",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Western",
            storyline: "In a marksmanship contest, Lin McAdam wins a prized Winchester rifle, which is immediately stolen by the runner-up, Dutch Henry Brown. This \"story of a rifle\" then follows McAdams' pursuit, and the rifle as it changes hands, until a final showdown and shoot-out on a rocky mountain precipice.",
            comments: "Good story.  Which was a change for Westerns at this time.  Before this, the bad guys were just bad, and were robbing banks, or stealing horses. The plot is complex for a western.  Although, it does get choppy at times.  Eventually, the intertwined stories become one story, and the chopiness diminishes.  But the camera shots are outstanding.  There is almost a film noir feel to it.  Hign-angle shots, low-angle shots with beautiful terrain, and beautiful use of the terrain and sets to accentuate the drama.  Shelley Winters' performance was a little flat in places, and outstanding in others.  But James Stewart was outstanding throughout.  Directed by Anthony Mann who also directed a number of film noir.  This is one of my favorites.",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "The Treasure of the Sierra Madre",
            production_co: "Warner Bros Pictures",
            release: "1948-01-24",
            last_viewed: "2006-08-01",
            my_rating: "9",
            afi_top_100: "38",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BOTJlZWMxYzEtMjlkMS00ODE0LThlM2ItMDI3NGQ2YjhmMzkxXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg",
            set: "Humphrey Bogart: Signature Collection - Volume 1 DVD",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Drama",
            storyline: "Fred C. Dobbs and Bob Curtin, both down on their luck in Tampico, Mexico in 1925, meet up with a grizzled prospector named Howard and decide to join with him in search of gold in the wilds of central Mexico. Through enormous difficulties, they eventually succeed in finding gold, but bandits, the elements, and most especially greed threaten to turn their success into disaster. ",
            city: "N/A",
            state: "Coahuila",
            country: "Mexico",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Wreck-It Ralph",
            production_co: "Walt Disney Animation Studios",
            release: "2012-11-02",
            last_viewed: "2015-01-17",
            my_rating: "8",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BNzMxNTExOTkyMF5BMl5BanBnXkFtZTcwMzEyNDc0OA@@._V1_SX300.jpg",
            poster: "FALSE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Adventure-Comedy-Animation",
            storyline: "Wreck-It Ralph longs to be as beloved as his game's perfect Good Guy, Fix-It Felix. Problem is, nobody loves a Bad Guy. But they do love heroes... so when a modern, first-person shooter game arrives featuring tough-as-nails Sergeant Calhoun, Ralph sees it as his ticket to heroism and happiness. He sneaks into the game with a simple plan -- win a medal -- but soon wrecks everything, and accidentally unleashes a deadly enemy that threatens every game in the arcade. Ralph's only hope? Vanellope von Schweetz, a young troublemaking \"glitch\" from a candy-coated cart racing game who might just be the one to teach Ralph what it means to be a Good Guy. But will he realize he is good enough to become a hero before it's \"Game Over\" for the entire arcade?",
            comments: "Outstanding CGI animated film.  The story itself has depth (which most animated films do not) - Wreck-it Ralph is good in his heart even though he is a \"Bad Guy\".  His encounter with Vanellope is a coincidence at first, and grows into a strong attachment when he finds that like him, she lives in a dump surrounded by garbage, and is fighting to change her circumstances.  Together, they overcome an evil pretender who steals Vanellope's place in the video-game.  Always a good watch, and a good story.",
            country: "Video Game",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "You Only Live Once",
            production_co: "Walter Wanger Productions",
            release: "1937-01-29",
            last_viewed: "2012-03-22",
            my_rating: "6",
            library: "Own",
            format: "https://m.media-amazon.com/images/M/MV5BOTYzZTUxN2EtOWVlYy00ZjMwLWI0NGQtMDNmNWRkNDg5MWJmXkEyXkFqcGdeQXVyMjA0MzYwMDY@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            nbr_of_discs: "1",
            genre: "Film Noir",
            storyline: "Joan is the secretary to the public defender in a large city. She is in love with a career criminal named Eddie, and she believes that he is a basically good person who just had some tough breaks. She uses her influence to get him released early, and he tries to go straight after marrying her, but things don't work out, and they both go on the lam.",
            comments: "Choppy plot.  Also, Hollywood corny.  Better dialogue would have helped too. No real low-key lighting.  Lang got in a couple of interesting shots.  The music is 1930s melodramatic. The low budget shows too.  Still, I would have expected Lang to do better.  I would love to ask him why he seemed to mail this one in.  Sylvia Sydney gave an excellent performance though, and Henry Fonda was outstanding.",
            city: "Unknown-fictional",
            state: "Unknown-fictional",
            country: "United States",
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            title: "Witness to Murder",
            production_co: "Chester Erskine Productions",
            release: "1954-04-15",
            last_viewed: "2015-06-03",
            my_rating: "6",
            format: "https://m.media-amazon.com/images/M/MV5BZTY5MTA1NjQtZTQ2Ni00ODJmLTkwNGYtYmQ4ZGIzOWY2OGY4XkEyXkFqcGdeQXVyMjUxODE0MDY@._V1_SX300.jpg",
            poster: "TRUE",
            night_at_the_movies: "FALSE",
            train_scenes: "FALSE",
            genre: "Film Noir",
            storyline: "Cheryl Draper (Barbara Stanwyck) sees a murder through her bedroom window, but no one will believe her. She is stalked by the suave killer ('George Sanders' ), who first takes steps to convince police she is crazy, but she has ally in a sympathetic policeman (Gary Merrill). ",
            comments: "Good, basic key-lighting.  A lot of the story occurs at night (almost too much).  There are a number of plot elements that are a \"stretch\".  The action at times is slightly disconnected - showing the plot jumps.  Another example is the detective discussing the case openly with a civilian and possibly mentally ill woman.  Some of the key scenes have excellent dramatic use of key-lighting.  It does have good pace and George Sanders is excellent.  It's a teaser, because this film had some unrealized potential.",
            createdAt: new Date(),
            updatedAt: new Date()
        }
    ], {});
  },
  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Films', null, {});
  }
};